# Generated by Django 3.1.3 on 2020-12-22 09:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201221_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(default=None, max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
