# Generated by Django 3.1.3 on 2020-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201222_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.IntegerField(),
        ),
    ]
